import { defineConfig } from 'tsdown';

// One bundle per public subpath. Each subpath maps 1:1 to a directory
// under `src/`; no all-in-one barrel and no convenience re-exports.

export default defineConfig({
  entry: {
    cell: 'src/cell/index.ts',
    chart: 'src/chart/index.ts',
    chartsheet: 'src/chartsheet/index.ts',
    drawing: 'src/drawing/index.ts',
    io: 'src/io/index.ts',
    node: 'src/node.ts',
    packaging: 'src/packaging/index.ts',
    schema: 'src/schema/index.ts',
    streaming: 'src/streaming/index.ts',
    styles: 'src/styles/index.ts',
    utils: 'src/utils/index.ts',
    workbook: 'src/workbook/index.ts',
    worksheet: 'src/worksheet/index.ts',
    xml: 'src/xml/index.ts',
    zip: 'src/zip/index.ts',
  },
  format: ['esm'],
  target: 'es2022',
  platform: 'neutral',
  // `node:*` builtins (used in src/io/node-fs.ts) are runtime-resolved
  // by Node — leave them as external imports so the bundle works in
  // both Node and browser targets without baking the implementation in.
  external: [/^node:/],
  sourcemap: true,
  clean: true,
  treeshake: true,
  // .d.ts is generated by `tsc -p tsconfig.build.json` so tsdown can stay focused on JS.
  dts: false,
  outDir: 'dist',
  // Force `.mjs` so the package.json exports map (which points at `.mjs`)
  // resolves regardless of `type: module` defaulting to `.js`.
  outExtensions: () => ({ js: '.mjs' }),
});
