import { defineConfig } from 'tsdown';

// One bundle per public subpath. xlsx-specific entries live under
// `xlsx/*`; format-agnostic byte I/O + node fs glue + low-level
// (zip/xml/schema/packaging/utils) live at the top level so they can
// be reused by future docx/pptx surfaces.

export default defineConfig({
  entry: {
    'xlsx/cell': 'src/xlsx/cell/index.ts',
    'xlsx/chart': 'src/xlsx/chart/index.ts',
    'xlsx/chartsheet': 'src/xlsx/chartsheet/index.ts',
    'xlsx/drawing': 'src/xlsx/drawing/index.ts',
    'xlsx/io': 'src/xlsx/io/index.ts',
    'xlsx/streaming': 'src/xlsx/streaming/index.ts',
    'xlsx/styles': 'src/xlsx/styles/index.ts',
    'xlsx/workbook': 'src/xlsx/workbook/index.ts',
    'xlsx/worksheet': 'src/xlsx/worksheet/index.ts',
    io: 'src/io/index.ts',
    node: 'src/node.ts',
    packaging: 'src/packaging/index.ts',
    schema: 'src/schema/index.ts',
    utils: 'src/utils/index.ts',
    xml: 'src/xml/index.ts',
    zip: 'src/zip/index.ts',
  },
  format: ['esm'],
  target: 'es2022',
  platform: 'neutral',
  // `node:*` builtins (used in src/io/node-fs.ts) are runtime-resolved
  // by Node — leave them as external imports so the bundle works in
  // both Node and browser targets without baking the implementation in.
  external: [/^node:/],
  sourcemap: true,
  clean: true,
  treeshake: true,
  // .d.ts is generated by `tsc -p tsconfig.build.json` so tsdown can stay focused on JS.
  dts: false,
  outDir: 'dist',
  // Force `.mjs` so the package.json exports map (which points at `.mjs`)
  // resolves regardless of `type: module` defaulting to `.js`.
  outExtensions: () => ({ js: '.mjs' }),
});
