import { defineConfig } from 'tsdown';

// Bootstrap-stage tsdown config: a single ESM entry from src/index.
//
// The eventual matrix (per docs/plan/11-build-publish.md §1.3) builds many
// subpath entries (read / write / streaming / styles / chart / chart-extended
// / drawing / pivot / schema / io-node / io-browser) with node and browser
// platform variants. That config lands when we have actual subpackage entries
// to point it at — not before. Keeping the surface narrow now means a CI
// build smoke can pass with no dead exports.

export default defineConfig({
  entry: { index: 'src/index.ts' },
  format: ['esm'],
  target: 'es2022',
  platform: 'neutral',
  sourcemap: true,
  clean: true,
  treeshake: true,
  // .d.ts is generated by `tsc -p tsconfig.build.json` so tsdown can stay focused on JS.
  dts: false,
  outDir: 'dist',
  // Force `.mjs` so the package.json exports map (which points at `.mjs`)
  // resolves regardless of `type: module` defaulting to `.js`.
  outExtensions: () => ({ js: '.mjs' }),
});
