// Public surface for the Cell value-model (CellValue + formula kinds +
// inline rich-text).

export type {
  Cell,
  CellValue,
  DataTableFormulaOpts,
  ExcelErrorCode,
  FormulaKind,
  FormulaValue,
  MergedCell,
} from './cell';
export {
  bindValue,
  cellHasComment,
  cellHasHyperlink,
  cellValueAsBoolean,
  cellValueAsDate,
  cellValueAsNumber,
  cellValueAsString,
  getCachedFormulaValue,
  getCoordinate,
  getFormulaText,
  isDurationValue,
  isEmptyCell,
  isErrorValue,
  isFormulaCell,
  isFormulaValue,
  isRichTextCell,
  isRichTextValue,
  makeCell,
  makeDurationValue,
  makeErrorValue,
  setArrayFormula,
  setCellValue,
  setDataTableFormula,
  setFormula,
  setSharedFormula,
} from './cell';
export type {
  InlineFont,
  InlineUnderline,
  InlineVertAlign,
  RichText,
  TextRun,
} from './rich-text';
export {
  appendRichTextRun,
  applyFontToRichText,
  clearFontsInRichText,
  concatRichText,
  countRichTextOccurrences,
  findAllRichTextIndex,
  findLastRichTextIndex,
  findRichTextIndex,
  getRichTextCharAt,
  getRichTextFontAt,
  insertRichText,
  isEmptyRichText,
  iterRichTextChars,
  makeRichText,
  makeTextRun,
  mapRichTextRuns,
  mergeAdjacentRichTextRuns,
  padEndRichText,
  padStartRichText,
  repeatRichText,
  replaceAllRichText,
  replaceRichText,
  reverseRichText,
  richText,
  richTextEndsWith,
  richTextEqual,
  richTextIncludes,
  richTextLength,
  makeTextRun as richTextRun,
  richTextStartsWith,
  richTextToLowerCase,
  richTextToString,
  richTextToUpperCase,
  richTextWords,
  setFontOnRichText,
  sliceRichText,
  splitRichText,
  splitRichTextRuns,
  trimEndRichText,
  trimRichText,
  trimStartRichText,
  truncateRichText,
} from './rich-text';
